### ISSUE TITLE
Build avec CircleCI

### ISSUE THREAD

**Issue by marc-bouvier** [lowdit/frago#18]
Nous somme en train de mettre en place Frago pour publier nos audits du site https://iroco.co

Comme nous utilisons la plateforme d'intégration continue CircleCI (comparable aux Github Actions). Voici un exemple de construction d'un site Frago sur cette plateforme.

Nous la compléterons avec un déploiement via Ansible (avec pour objectif de créer un rôle Ansible réutilisable par la communauté).

https://github.com/iroco-co/audits-frago/blob/main/.circleci/config.yml

Voici notre script de CI à l'heure actuelle :

`.circleci/config.yml`

```yml
version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

workflows:
  generate-audits:
    jobs:
      - hugo/build:
          version: 0.120.3
          hugo-extra-flags: --config hugo.toml
          html-proofer: false
          pre-steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
          post-steps:
            - store_artifacts:
                path: public
                destination: audits
```
