### ISSUE TITLE
Intérop entre NumEcoDiag et Frago

### ISSUE THREAD

**Issue by marc-bouvier** [lowdit/frago#32]
Coucou @bertrandkeller , avec Bruno de Iroco, on a forké l'extension NumEcoDiag pour supporter la v2 du RGESN.
On en a profité pour ajouter un export CSV au format Frago.

https://github.com/iroco-co/NumEcoDiag

![Screen Recording 2024-11-28 at 13 21 47(2)](https://github.com/user-attachments/assets/934de7b7-c90c-4aa3-a158-1877dd78b8dc)

**Comment by brtrdkeller** [comment]
Hmm, why not.

Attention le RGESN (euh qu'il s'appelle toujours V1 à l'ARCEP, je crois mais qu'on nomme V2 parce que faut bien changer de nom de répertoire) est un audit hybride.

Il demande le justification à gogo et des appels à des ressources "preuves". Les preuves peuvent être nourries par d'autres fichiers preuves. Il est aussi possible de "merger" des fichiers de déclaration car un service numérique peut-être composé de plusieurs services numériques (Et oui).

C'est un boorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdel. Que les concepteurs n'ont certainement pas encore compris.

```
website: "example.gouv.fr"
contacts:
    email: referent@ecoresponsable.gouv.fr
    address : 139 rue de la sobriété, 75572 Paris, Cedex 23
audits:
    2024-05-01:
      guidelines: "RGESN 2.0"
      condition: "Auto-évaluation"
      criteria:
        - id: "1.1"
          norms:
            - Norme 1
            - Norme 2
          description: |-
            Voluptate cupidatat adipisicing veniam commodo tempor et nulla ea magna non.
              * Ullamco nostrud nostrud qui.
              * Voluptate dolor elit tempor ullamco duis.
        - id: "1.2"
          studies:
            - Mon étude 1
            - Mon étude 2
            - Mon étude 3
          target:
            - les Agents
            - les gens sympas
          functionalities:
            - Ma fonction 1
            - Ma fonction 2
            - Ma fonction 3
```

Dans Frago, il faut éditer un fichier YAML. Qui sera certainement refusé par les auditeurs, juste à cause de la syntaxe.
Il faut trouver un moyen d'éditer ce fichier qui s'appelle : context.yml.
