### ISSUE TITLE
Déclaration d'accessibilité

### ISSUE THREAD

**Issue by mloyat** [lowdit/frago#41]
Les commentaires de l'auditeur n'apparaissent plus sous les erreurs qui remontent dans la déclaration d'accessibilité. La map "criterion" semble ne pas exister...

![Image](https://github.com/user-attachments/assets/ab8e7a5e-4686-423e-ad38-5f3d2bce995c)

**Comment by bertrandkeller** [comment]
Dans la déclaration ?

On veut les commentaires dans la déclaration ? Je ne crois pas que ce soit prévu.

Est-ce qu'on fait quelque chose ?

**Comment by mloyat** [comment]
Ah ? Il me semblait que le morceau de code de validity.html qui recense les erreurs sur les différentes pages était là pour ça... Désolé.
Un utilisateur handicapé peut avoir un grand intérêt à lire ce qui cloche sur le site pour savoir s'il va être impacté ou non, et ce, avant même de naviguer sur le site. 
Par ailleurs, sur la page dédiée du site du RGAA, ça parle de "un signalement des contenus non accessibles".
À méditer...

**Comment by bertrandkeller** [comment]
Moi ce que je n'ai pas dans les commentaires qui viennent de la feuille c'est que l'affichage est pas terrible.
Pour moi, les commentaires ne sont que des preuves d'audit.

Il faut que je regarde, mais l'idée était de remonter plutôt les recommandations dans la déclaration. Ça me dit quelque chose ce truc. Et là Frago est génial, car tu lis les 2 rapports dans la déclaration.

**Comment by mloyat** [comment]
Pour moi, le commentaire exprime ce qui cloche :
```Le lien dans l’encart des données personnelles n’offre pas un contraste suffisant (3.85 au lieu de 4.5)```

La reco va être ```Augmenter le contraste```

Il me semble plus pertinent d'inclure les commentaires qui vont donner une information à l'utilisateur de ce qui pose problème et si ça le concerne.

**Comment by mloyat** [comment]
Oui, ça demande à être réfléchi. La déclaration peut vite devenir indigeste... 
Plutôt que de reprendre tous les commentaires, on pourrait imaginer d'intégrer un texte produit par l'auditeur (dans le yaml de contexte ?).

Cela permettrait de donner des indications précieuses pour les critères bloquants sans surcharger la déclaration.
```
audits:
  2025-02-27:
    guidelines: "RGAA 4.1"
    ...
    declaration:
      errors:
        - criterion: 6.2
          description: "Les liens sont tout pétés sur les pages d'accueil et des conditions d'absorption" 
        
        - criterion: 7.1
          description: "La fenêtre modale du menu mobile ne conserve pas le focus et n'implémente pas le motif de conception ARIA Modal"
```
