### ISSUE TITLE
Confusion entre le nom du projet et le nom de l'organisme dans la déclaration de conformité

### ISSUE THREAD

**Issue by firewalkwizme** [lowdit/frago#8]
### Confusion entre le nom du projet et le nom de l'organisme dans la déclaration de conformité

Dans la déclaration, 

- le nom de l'organisme est repris à tort juste après "État de conformité" : [Nom de l'organisme](à supprimer selon moi) [Nom du projet] est non conforme avec le référentiel général d’amélioration de l’accessibilité (RGAA), version 4 en raison des non-conformités et des dérogations énumérées ci-dessous.
- le nom du projet est repris à tort juste après Si vous n’arrivez pas à accéder à un contenu ou à un service, vous pouvez contacter le responsable de [Nom de l'organisme], [Nom du projet] (à supprimer selon moi) pour être orienté vers une alternative accessible ou obtenir le contenu sous une autre forme.

Merci.

**Comment by bertrandkeller** [comment]
Merci

Je pense qu'il y a pas mal d'erreurs ou améliorations à apporter aux déclarations.
Je n'ai pas poussé le sujet en profondeur

**Comment by bertrandkeller** [comment]
@firewalkwizme - Je t'oublie pas.

Je me suis lancé sur les twittercards pour chacun des rapports. Je sais pas si tu en aurais l'utilité.
C'est fait pour les équipes qui ont un frago et des réunions récurrentes… et utilisent Slack ou Mattermost.
Un dev que je veux faire depuis 2 ans et j'ai trouvé comment faire.

Est-ce ton besoin est pressé ? Est-ce que tu as d'autres demandes sur Frago ?

**Comment by bertrandkeller** [comment]
C'est bon c'est poussé.

L'url du site est affiché sous forme de lien.
J'ai ajouté les données d’environnements pour que ça respecte la loi : 

```
environment:
        - OS: Windows 11
          screenreader: NVDA (dernière version)
          browser: Firefox
          type: desktop
        - OS: "MacOS"
          screenreader: VoiceOver (dernière version)
          browser: Safari
          type: desktop
        - OS: "Androïd natif"
          screenreader: TalkBack (dernière version)
          browser: Chrome
          type: mobile
        - OS: "iOS"
          screenreader: VoiceOver (dernière version)
          browser: Safari
          type: mobile
```
